services:
  mysql:
    image: mysql:8.0
    container_name: eth-wallet-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  redis:
    image: redis:8-alpine
    container_name: eth-wallet-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: eth-wallet-kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  localstack:
    image: localstack/localstack:3
    container_name: eth-wallet-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: kms
      DEFAULT_REGION: ap-northeast-2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  wiremock-mainnet:
    image: wiremock/wiremock:3x
    container_name: eth-wallet-wiremock-mainnet
    ports:
      - "9090:8080"
    volumes:
      - ./infra/wiremock/mainnet/mappings:/home/wiremock/mappings:ro
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

  wiremock-octet:
    image: wiremock/wiremock:3x
    container_name: eth-wallet-wiremock-octet
    ports:
      - "9091:8080"
    volumes:
      - ./infra/wiremock/octet/mappings:/home/wiremock/mappings:ro
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

volumes:
  mysql-data:
